### ISSUE TITLE
You have an old version of fpcalc. Please upgrade to 1.4.3.

### ISSUE THREAD

**Issue by screwfaze** [linuxserver/docker-lidarr#14] opened 2019-03-08 13:52 UTC
Hi,

First of all thanks so much for all the awesome Docker Containers I am using so many. Just wanted to let you know that on the latest Lidarr I am having this error "You have an old version of fpcalc. Please upgrade to 1.4.3." which I was told by Lidarr devs to ask you guys for a fix.
My host OS is Ubuntu Server 18.04 LTS.

Thanks

**Comment by Qstick** [comment] 2019-03-09 01:03
Dupe of #13 please close

**Closed** 2019-03-09 01:07 UTC
